[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrpvv5xpf3h3x7rdr79gucym5vgdwsz6aamvpv9lqkq8lnefsnkpjfuet8a"]

[[validator_account]]
address = "tnam1qxytglp7k0c0s8gk2t57ahv7kugaxga6rc7fxcf0"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.89.5:36656"

[validator_account.consensus_key]
pk = "tpknam1qqft89xmr6c8s2lpzdvl9k3375melf0tvtyk70ynyejtxq4hhzrak9ykmh6"
authorization = "signam1qqyq0dcw8u9h8q9kvhdt4q3l6w25ucut3qwhrddq65upma7hu230zfr0qtz0plsdslshsdq403hgmaye2uxzga5deks57dlsqpysxdqxt8xh80"

[validator_account.protocol_key]
pk = "tpknam1qqrq8nkspr7ljd87hjnt0h3c5enx7xeja2t6cfea2g5qyzth6u865xrwg3e"
authorization = "signam1qqjm93t7fw7v6xk8yd0av3ks8ww78w2stfhy0xvcytrlwc8gha0hh7l7k50aueazprnflaydapx7afyl6t2lnpsn4gjacwvctaa7cqqppg7ycz"

[validator_account.tendermint_node_key]
pk = "tpknam1qpxr38e8fp0q8x087vwg48scz9ypxvymqmgrqte8vs5wm4yd3fch5l626jw"
authorization = "signam1qrqpkqc9jh42nle76hr22rvxrwag2d24fjkmg2tdygnt0y9wqch2ultuucje049kyln9ywt8d6hjflv8y2qge4zw0yl0vg7tj20yexsy6sf059"

[validator_account.eth_hot_key]
pk = "tpknam1qyprx0lssd9vc6umlv80jrv0sva9shqkmn7pc3cs87zua280nfr774sauxyz8"
authorization = "signam1qx5asfewuknl9tv8dv2lc4z6c0ehdyn0tjjwztjseynevnsa2akwx8qj3fs20gaczjnwwehtvm05f82rau3gaqhlvfds2mzlz7kvevr7qq6dk7ag"

[validator_account.eth_cold_key]
pk = "tpknam1qyps0m0ducxv8xm2fj4skm3c8mgk9ukrh8k56j39mdpvqvdjqr2ltmslppjlx"
authorization = "signam1qxjsq5g27jrxe0m6gwwvg7vfflcscpvd7zhzau548q2s938hp8wszvy67a3cgslduyla2ten4yyn2hpnedrpej5grapfzv367nv66f5yqyjyed96"

[validator_account.metadata]
email = "hello@2pilot.dev"
twitter = "stanisloe"
discord = "stanisloe"

[validator_account.signatures]
tpknam1qrpvv5xpf3h3x7rdr79gucym5vgdwsz6aamvpv9lqkq8lnefsnkpjfuet8a = "signam1qqavutq0ylvh2q34xxzys04jp8ltf50902xqhqe2w7w09k6x9yxftpwyjuls3p4meh5egshrqwch7pyqvldyv80gdz2wd6t67fwpdtsvsfc7xn"

[[bond]]
source = "tnam1qxytglp7k0c0s8gk2t57ahv7kugaxga6rc7fxcf0"
validator = "tnam1qxytglp7k0c0s8gk2t57ahv7kugaxga6rc7fxcf0"
amount = "1000000"

[bond.signatures]
tpknam1qrpvv5xpf3h3x7rdr79gucym5vgdwsz6aamvpv9lqkq8lnefsnkpjfuet8a = "signam1qpa02wf3seu7g9ss20n4l7aryt023r2chk9dy6ec3fpav06gklazt7ypgq9270wyh0ph0m9yyrsfp7ghp5z8f5avlkvvcl6q2jzwyjqgzr5ncd"
