[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqxce0dvv8fwh96nxj6m07kmlds504vhkj4ufjzxwlunry4sm6xfykdsesg"]

[[validator_account]]
address = "tnam1q874dtrvs68lxaskmf4s8kw7w3sygu33uvyl8mve"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "157.90.183.32:26656"

[validator_account.consensus_key]
pk = "tpknam1qzrkcp5284plvkghlrm7rhjtshwv6ljy0sxwhtn80lpprnp8d960zdxjqrk"
authorization = "signam1qzgd4hw4jf57ygjhzj4gwn6r3wdp3kal863ntxs0wenxeut5zzqnvgzd44g85njxlpddanrxmh39rhu5hrvjeh30udy0rx8nrycqa3qpme20sk"

[validator_account.protocol_key]
pk = "tpknam1qq7qs6gux63rjfxhutv3w3asjjfu2dz2z6gk56xu7tad88gudkp7jk4uxg7"
authorization = "signam1qqjezdn8705jldzhx5e2n8lxwhe2xwkgxncujec2vplm9ltwaua77764g9fnl0qn677uj2udqhlm3k04303edg6jxtvwv8cfrkdsmtqw9e9g0p"

[validator_account.tendermint_node_key]
pk = "tpknam1qq6ee805vy96n83yag5d33fwunhz3vq58as5nq4wd9wclhdn940wgt7yuye"
authorization = "signam1qpdgr9jrmpqugwa42xgaypexvrhpkq34vhy2q3lzd76r9qp60gzvqmfss0jsu69cf3c5kf5q043htjt2h5f0l036fungg68nkkmhwygvl9ggdj"

[validator_account.eth_hot_key]
pk = "tpknam1qyp0290t98stq2f6vsnfgtmuw2mnamst83kmnq90y39pffercmjp9gqyfrx05"
authorization = "signam1qxnq0ckt7wwpkyqy6jzll4kdxjkqx509ln6gtctpsfhzs2tkwq7my74qre00eww4ycnfafa95fgw97y77f8dzh7v35fpe9al03l9f28zqymg6lg5"

[validator_account.eth_cold_key]
pk = "tpknam1qypmhcfevngmafaecmc3pp5fpl793xvnthncqjveyy40xuqpg2q5lgqm66rx3"
authorization = "signam1qx3tlmu25mr2pmdwhk07cngsh5xknzh9cnmqtujj2vl37tuw3fffxkjjl4ee6t6pra830kjxff8k6sar3c550jevlxqsn5sarudfyeu9qyjux06v"

[validator_account.metadata]
email = "ekh@tuta.io"
discord = "0xb0b"
elements = ""
telegram = ""
twitter = ""
[validator_account.signatures]
tpknam1qqxce0dvv8fwh96nxj6m07kmlds504vhkj4ufjzxwlunry4sm6xfykdsesg = "signam1qrn8rvpkqcum3epswnmgzpwrwrfhjwuzeq237gkwjyu7apd02qpgu4au9ajj3e02w7epfqdmvlkdachz83t7lw6vzu8cdx6t3t5fvys95r6das"

[[bond]]
source = "tnam1q874dtrvs68lxaskmf4s8kw7w3sygu33uvyl8mve"
validator = "tnam1q874dtrvs68lxaskmf4s8kw7w3sygu33uvyl8mve"
amount = "1000000"

[bond.signatures]
tpknam1qqxce0dvv8fwh96nxj6m07kmlds504vhkj4ufjzxwlunry4sm6xfykdsesg = "signam1qztl9qtwwzg4xdndrzlyn6jvyq5sxf6ejy5gzu823xpkry6wrfhk90p4anujzxkn8zecrdw2zg4tsw5w4sr0k76z9vrw5y46j792hhct2mn7ny"
