[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqamym54y3rq678p9j7lkkgy3prvdyz3nnxds7k7ff7vgdr0rfst5hwr7c2"]

[[validator_account]]
address = "tnam1qy3pw36fs0jyj0y6edffruk83tpuup2cvsupua39"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.03"
net_address = "65.108.13.212:26656"

[validator_account.consensus_key]
pk = "tpknam1qq7l2xg3pggeumy493paxxnyy6g6fg5x5n5tmnkk32egts4kut0qgexwj0l"
authorization = "signam1qqlhq2yec76awdsx4g6ejtzgllfl8vhrrkgu936huph3802mpygkmzthv7qzcutan96x7jqu8qtaatuy7ngp3qsxsk4tftrg66gt6cc87axjjy"

[validator_account.protocol_key]
pk = "tpknam1qrv0lpvqa5yzef3u6jxrgkv4v35cdmdpdhy50hmnwurq709svezy6898p74"
authorization = "signam1qrmfeplhc0nucnyy2hndx72unhmfkf4rg42ly6cmjfwyladc0hqahtde0sx8hvenga4fmnlz6zf3xr7sl3f5nxrtctdcdjues37350s0jjv3vk"

[validator_account.tendermint_node_key]
pk = "tpknam1qrm480ch6w7pd0zrnkppclpx6hvr0rqjs0w7fgzq5zmcg3ncp0u6ujt8nwa"
authorization = "signam1qzkqjzwdmedxavrp69c8vt35r2mgtv87t5m3st0djupvn3cvv244x72pe874ckccfycm4u4f503akcjj44rh2u33etz5xqyc749k3aq84uhtdd"

[validator_account.eth_hot_key]
pk = "tpknam1qypg6uvccdt0k0535wg7zm43txwslahthf653zcds2ynt2tm0gtpfkg3la4ee"
authorization = "signam1q8w5rfhm50sxxk4hagc4hmh7wgxsr6g653fr3tdpx8xdjl5j6khucmmtdssdjt272hx4pw8nysd6fcnnzupux4pygf8w3tjjctgzgq9rqy3dtvzq"

[validator_account.eth_cold_key]
pk = "tpknam1qyp35z49lcey0h50g99xyvxqmjquqrfv8gm0swqcqlktrc64u26nezstac8jc"
authorization = "signam1q8l54gk03at7qwudfwcgrklv4xur6lmjlqwwllg6uleq76g27cpvsrd2qfv8l0dnlursf8ztqv0g077h7g3afnxkxptmmad3m57c36gfqq85w925"

[validator_account.metadata]
email = "n75pro@protonmail.com"
discord = "shurinoff"
twitter = "theNode75"
elements = ""

[validator_account.signatures]
tpknam1qqamym54y3rq678p9j7lkkgy3prvdyz3nnxds7k7ff7vgdr0rfst5hwr7c2 = "signam1qp5c4p8k3m4mpk4vxj7eajfns6smwka96uvpex5q0ckh6ug0czyvtgwj9ds3r6rhscxr08xpqwwakcs5ngm4fs56wz79yrclkzdj00qxt85ngx"

[[bond]]
source = "tnam1qy3pw36fs0jyj0y6edffruk83tpuup2cvsupua39"
validator = "tnam1qy3pw36fs0jyj0y6edffruk83tpuup2cvsupua39"
amount = "1000000"

[bond.signatures]
tpknam1qqamym54y3rq678p9j7lkkgy3prvdyz3nnxds7k7ff7vgdr0rfst5hwr7c2 = "signam1qr75jpgfaq930he5d2hlrz9h5k5jp48ngvant00vk75zqmz49udwh3z9png2f5ghtxgrw5lr9e66hcpmyyke5yty7k4h0q6ddak2hds90pvcef"
