[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qpnnkxv7m6rlgt8vaarz0uakhlay4tm3xr9mlnmqmft0ndztkhhewvme92e"]

[[validator_account]]
address = "tnam1q8htcaruytqfuer2grxtrhkyp8nht4mpvg8pz5yh"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "212.51.129.74:26656"

[validator_account.consensus_key]
pk = "tpknam1qr5r8nx4yj52jne8ledrxtgwla27p9gl0dh5g679qneun205ugpzsczfr3t"
authorization = "signam1qq4nrpg474glf94g7706nq7p8xv59x7frs53f53sk2ej7js5kkhsmptgl7m97xh4kt5hhawhmqsms6xswu7wxy5nq7wpem02zhg2d8gwg7grsa"

[validator_account.protocol_key]
pk = "tpknam1qrnl9el30m03mfg8mcvnjh7v5cuz5jfp4jqswdrf9p6q9ltpekl2vknt0qs"
authorization = "signam1qp0h7hudwwj3lwfq03eu5jufswlyct7yddyrejfs73l70ekwjjgp7msz0x4p47ezt4z2egry96ynrjf92t59sv6dk9f4hsr6c99rkusgc6kvw6"

[validator_account.tendermint_node_key]
pk = "tpknam1qz0w5e86s5tr8tratzvk6cmeq36ml8033zymwy7syuy8le0xrf4y7drqc43"
authorization = "signam1qq9mjye9f96dw3c2jcdejg62tvkuxaqpv093l0e6e66lvhfgvr8uadpv4txx0x2hwv2azeps4z5s4nlsm90kwcnaqy29glu2ejstu3gxqkx7hg"

[validator_account.eth_hot_key]
pk = "tpknam1qypuc042kk4vtf9zfd3ezp8rc829e0wp4yudq2w0m93p6vanrjlexegzprjxw"
authorization = "signam1q9ufrs3n28yv8nq0xzkjhthul4mzhamsqz5gr63sl9a79ssqt6h0jezcsxrfaljdke0h974l0y8e0qlhagxen20ag58zxnk8hcd8j3wjqy27w828"

[validator_account.eth_cold_key]
pk = "tpknam1qyp62qgu83g5py6a6vnnq65247dkfe4z9u4n6k5h7uzmlx4r2qcpaegcj5vmh"
authorization = "signam1q8ey0eyh5jmhgpj3w0vs5454kd09e5de5fqs0awtv2k69kkwk7pwkp8k6s5amevg7fdvjh72zkpa9emk5hsjrl4pcvavrk0tkeqspqu5qqvun33t"

[validator_account.metadata]
email = "renato.delgaudio@gmail.com"

[validator_account.signatures]
tpknam1qpnnkxv7m6rlgt8vaarz0uakhlay4tm3xr9mlnmqmft0ndztkhhewvme92e = "signam1qrk9u95njwfclqz7mmyyn8xytumhtn6fg3rpnquv5h9s4txrqwkf8z00m2ecajm9mtm7aexauf9lhrt5e9nmplxe542gey8pymaj4jqpfg7ktc"

[[validator_account]]
address = "tnam1q8htcaruytqfuer2grxtrhkyp8nht4mpvg8pz5yh"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "212.51.129.74:26656"

[validator_account.consensus_key]
pk = "tpknam1qrhchzx0l4r4t6zck0zyttkrlps5kjv9mr295ynh2hv5pt7jx7027tvkwyp"
authorization = "signam1qz480t25v003v2qfnp80f89js4pmm6v0hmzlv4jaxz5maf5zwls3g4v94vjqtw8df2p0saah9uccqekv9a8rvucvjg0n966z8kdwmqqv6t7nlu"

[validator_account.protocol_key]
pk = "tpknam1qr6v0lrpt2wlwtpj9yqcs4df0w22d5lqga792tqmu95q6ver8nds7wxnfmp"
authorization = "signam1qp6emu4x26lwl98rxe3t2p5xjhh2tgxs4jaf3h75tmzh8f2ad6unu5hawgf8eexyfrv3h76r8hc4ds3a8rp7lvm44ggeqemcy7wfdjcyjmk096"

[validator_account.tendermint_node_key]
pk = "tpknam1qzqh3stdjcnptad47tjmdpghs86pgrquncl2s4a70zs3lthxn2fgk7q2gc6"
authorization = "signam1qrl94dqa237wfvx26nr7kzngrmjc67m9yma3xgcrrcenlv7cslstqa3tzglw9xdx5vdynrtafsrwmw2vf84yv58yd4rxdfvdrp3fcvgrznpk4v"

[validator_account.eth_hot_key]
pk = "tpknam1qyptmaw4rlccg9aqj4try0axrgqm2l3e2n72jv35fa0etqhqpc0cphqrknxke"
authorization = "signam1qxpvkz3hegnfaph2gfe2g9ar0hm0pt5l2s42cxjgl48qn0slrk727dflkgx0m8llezqwerg282ux204p7x4z6fnwzsacs3scekln7p9mqqr8qfy8"

[validator_account.eth_cold_key]
pk = "tpknam1qypj6de5samyy3eyykl9hnn0xlgyhhyxlcvxu0hzdunggtq2fnf8sjsqu6lrl"
authorization = "signam1qxmsc0akdwy6t93j7vzthzqh2pfuue04l2tr6clcg7jwsstc4p5jy8u2tlhuk4mgscct3uzegfes6n76wwmww0fxhnmqglfzfdh6ng2hqqfgnn4c"

[validator_account.metadata]
email = "renato.delgaudio@gmail.com"
discord_handle = "scaniacrypto"

[validator_account.signatures]
tpknam1qpnnkxv7m6rlgt8vaarz0uakhlay4tm3xr9mlnmqmft0ndztkhhewvme92e = "signam1qp3xyhxe3jedfhwdrpnk55ue7u4t327l9yrf0nzp6k9f8g9d29ngzewpsnad0spk86dcrk7la37w92qhmlhjyyazv34cjl0znax4qcqdjgq20m"

[[bond]]
source = "tnam1q8htcaruytqfuer2grxtrhkyp8nht4mpvg8pz5yh"
validator = "tnam1q8htcaruytqfuer2grxtrhkyp8nht4mpvg8pz5yh"
amount = "1000000"

[bond.signatures]
tpknam1qpnnkxv7m6rlgt8vaarz0uakhlay4tm3xr9mlnmqmft0ndztkhhewvme92e = "signam1qz0y86ycq2cx8pl0n2hx8ylygt667zm6ff2saqcefmn6h6hww2hy3y8t8fmu03ddr9h974zx4v9f48qgvzftq45uswu3cdazm70fhdcwcwwg4s"


