[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qz2gej39emwh2eye8j2urrlfuzng3sxryqhh5mnygy0g8lfnyadly7v29ku"]

[[validator_account]]
address = "tnam1q9l958vd35ur0zap4sd3zc3g4q8tfhe0mgha30tk"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.43.113:26656"

[validator_account.consensus_key]
pk = "tpknam1qqd42c7jflgrcmvw3xgpegpq0mstvgjsxu9ayacapwtwpr09yvnrqka7qyu"
authorization = "signam1qqf5h2dnu24kx02ht5nmds24kmzxsz35zs5thxhs78azdpfs0t3aefy9slze0yc3zrte2u8xsztfkdha3788pa4r80al2t2gw7s5hus9e0zlyy"

[validator_account.protocol_key]
pk = "tpknam1qq0cpumptm3q7wth7l3c5r90k4pn3np7dyr6mzeejfhx2zxkqnxzzdpgzkp"
authorization = "signam1qry0w3hxp6z89ad0z74mavgnprq24kw83rmu2tcwucmjjxqq43tknlvnmq8hvmgtgxmle6d4zd4vuwe9zq4awk5kfxm9ppegh3ay8xcvl5qsnc"

[validator_account.tendermint_node_key]
pk = "tpknam1qpvkdqn054qzwe5guarqsgzt7cn98mg4ecdjage4jmj26d5q5ly9zchg7gu"
authorization = "signam1qrlyx5cqahpwnqqww4c8der8qursy9sl3qcv0ksc7kl0zyyy4v4tvx0mm4c2dhznkhl0r6axvl5lgaqgq9yqwthlssnwuwcyewv5t3qtzmqquj"

[validator_account.eth_hot_key]
pk = "tpknam1qypg3av6hztuvgpd43tq68x3rp4dn6j5s9txtm8hjkvj8x99tk6fzdsc96zdh"
authorization = "signam1q87uhjcz3fncur9xeup348ynjm0lg47rpljwvptd8qf2klg4dmxkqhk9af8mxtvz29t7c7pwqr6k4ykxhuulzx8vfngy4dr35zyct6x7qykrytks"

[validator_account.eth_cold_key]
pk = "tpknam1qypjwm8g433rpkry7gz9kymqjzpd6ryk8mnwqdzqzvqwaj32lk7q25qlksqh7"
authorization = "signam1qxweefazfhydxsp5kktpnn6cs0jgfvru8tsprqyanxn9ewrzc3g3kcpw0tvhhtymul3z69fv2pkd2x8fcus0vtkhrcr5j6lrmm6tah40qy2nxasy"

[validator_account.metadata]
email = "tecnodes.network@gmail.com"
discord = "tecnodes"
twitter = "@TecnodesNetwork"
elements = ""

[validator_account.signatures]
tpknam1qz2gej39emwh2eye8j2urrlfuzng3sxryqhh5mnygy0g8lfnyadly7v29ku = "signam1qp2qcqper0qwhghtyj7uzv5x9afqkc58m576ndj0usw5qugvxqkcfrs8nycjs6wat34ax9tls9e27rddy03x5z47r8w3c8x3zwweq4sp97gak6"

[[bond]]
source = "tnam1q9l958vd35ur0zap4sd3zc3g4q8tfhe0mgha30tk"
validator = "tnam1q9l958vd35ur0zap4sd3zc3g4q8tfhe0mgha30tk"
amount = "1000000"

[bond.signatures]
tpknam1qz2gej39emwh2eye8j2urrlfuzng3sxryqhh5mnygy0g8lfnyadly7v29ku = "signam1qphlgsqrw6pl5melfzyt22ulxauty84m4g2c34teyp3jq86mpr757tfcgmqdev399e9kjwz6sw89sy5hz3824ffzgp0nsmpgc4egexqvwxtm3p"
